/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jni_one_HelloNative */

#ifndef _Included_com_jni_one_HelloNative
#define _Included_com_jni_one_HelloNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jni_one_HelloNative
 * Method:    sayHello
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_jni_one_HelloNative_sayHello
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_jni_one_HelloNative
 * Method:    myTest
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jni_one_HelloNative_myTest
  (JNIEnv *, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
