// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FeatureAdd.proto

package pro.add;

public final class FeatureAdd {
  private FeatureAdd() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TaskDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pro.add.TaskData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string cmd = 1;</code>
     */
    String getCmd();
    /**
     * <code>string cmd = 1;</code>
     */
    com.google.protobuf.ByteString
        getCmdBytes();

    /**
     * <code>string water = 2;</code>
     */
    String getWater();
    /**
     * <code>string water = 2;</code>
     */
    com.google.protobuf.ByteString
        getWaterBytes();

    /**
     * <code>string person_id = 3;</code>
     */
    String getPersonId();
    /**
     * <code>string person_id = 3;</code>
     */
    com.google.protobuf.ByteString
        getPersonIdBytes();

    /**
     * <code>int32 group_id = 4;</code>
     */
    int getGroupId();

    /**
     * <code>repeated .pro.add.AddFeature feature_list = 5;</code>
     */
    java.util.List<AddFeature>
        getFeatureListList();
    /**
     * <code>repeated .pro.add.AddFeature feature_list = 5;</code>
     */
    AddFeature getFeatureList(int index);
    /**
     * <code>repeated .pro.add.AddFeature feature_list = 5;</code>
     */
    int getFeatureListCount();
    /**
     * <code>repeated .pro.add.AddFeature feature_list = 5;</code>
     */
    java.util.List<? extends AddFeatureOrBuilder>
        getFeatureListOrBuilderList();
    /**
     * <code>repeated .pro.add.AddFeature feature_list = 5;</code>
     */
    AddFeatureOrBuilder getFeatureListOrBuilder(
            int index);
  }
  /**
   * Protobuf type {@code pro.add.TaskData}
   */
  public  static final class TaskData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:pro.add.TaskData)
      TaskDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TaskData.newBuilder() to construct.
    private TaskData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TaskData() {
      cmd_ = "";
      water_ = "";
      personId_ = "";
      groupId_ = 0;
      featureList_ = java.util.Collections.emptyList();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TaskData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();

              cmd_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              water_ = s;
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              personId_ = s;
              break;
            }
            case 32: {

              groupId_ = input.readInt32();
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                featureList_ = new java.util.ArrayList<AddFeature>();
                mutable_bitField0_ |= 0x00000010;
              }
              featureList_.add(
                  input.readMessage(AddFeature.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          featureList_ = java.util.Collections.unmodifiableList(featureList_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return FeatureAdd.internal_static_pro_add_TaskData_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return FeatureAdd.internal_static_pro_add_TaskData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              TaskData.class, Builder.class);
    }

    private int bitField0_;
    public static final int CMD_FIELD_NUMBER = 1;
    private volatile Object cmd_;
    /**
     * <code>string cmd = 1;</code>
     */
    public String getCmd() {
      Object ref = cmd_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        cmd_ = s;
        return s;
      }
    }
    /**
     * <code>string cmd = 1;</code>
     */
    public com.google.protobuf.ByteString
        getCmdBytes() {
      Object ref = cmd_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        cmd_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int WATER_FIELD_NUMBER = 2;
    private volatile Object water_;
    /**
     * <code>string water = 2;</code>
     */
    public String getWater() {
      Object ref = water_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        water_ = s;
        return s;
      }
    }
    /**
     * <code>string water = 2;</code>
     */
    public com.google.protobuf.ByteString
        getWaterBytes() {
      Object ref = water_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        water_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PERSON_ID_FIELD_NUMBER = 3;
    private volatile Object personId_;
    /**
     * <code>string person_id = 3;</code>
     */
    public String getPersonId() {
      Object ref = personId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        personId_ = s;
        return s;
      }
    }
    /**
     * <code>string person_id = 3;</code>
     */
    public com.google.protobuf.ByteString
        getPersonIdBytes() {
      Object ref = personId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        personId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GROUP_ID_FIELD_NUMBER = 4;
    private int groupId_;
    /**
     * <code>int32 group_id = 4;</code>
     */
    public int getGroupId() {
      return groupId_;
    }

    public static final int FEATURE_LIST_FIELD_NUMBER = 5;
    private java.util.List<AddFeature> featureList_;
    /**
     * <code>repeated .pro.add.AddFeature feature_list = 5;</code>
     */
    public java.util.List<AddFeature> getFeatureListList() {
      return featureList_;
    }
    /**
     * <code>repeated .pro.add.AddFeature feature_list = 5;</code>
     */
    public java.util.List<? extends AddFeatureOrBuilder>
        getFeatureListOrBuilderList() {
      return featureList_;
    }
    /**
     * <code>repeated .pro.add.AddFeature feature_list = 5;</code>
     */
    public int getFeatureListCount() {
      return featureList_.size();
    }
    /**
     * <code>repeated .pro.add.AddFeature feature_list = 5;</code>
     */
    public AddFeature getFeatureList(int index) {
      return featureList_.get(index);
    }
    /**
     * <code>repeated .pro.add.AddFeature feature_list = 5;</code>
     */
    public AddFeatureOrBuilder getFeatureListOrBuilder(
        int index) {
      return featureList_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getCmdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, cmd_);
      }
      if (!getWaterBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, water_);
      }
      if (!getPersonIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, personId_);
      }
      if (groupId_ != 0) {
        output.writeInt32(4, groupId_);
      }
      for (int i = 0; i < featureList_.size(); i++) {
        output.writeMessage(5, featureList_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getCmdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, cmd_);
      }
      if (!getWaterBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, water_);
      }
      if (!getPersonIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, personId_);
      }
      if (groupId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, groupId_);
      }
      for (int i = 0; i < featureList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, featureList_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof TaskData)) {
        return super.equals(obj);
      }
      TaskData other = (TaskData) obj;

      boolean result = true;
      result = result && getCmd()
          .equals(other.getCmd());
      result = result && getWater()
          .equals(other.getWater());
      result = result && getPersonId()
          .equals(other.getPersonId());
      result = result && (getGroupId()
          == other.getGroupId());
      result = result && getFeatureListList()
          .equals(other.getFeatureListList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CMD_FIELD_NUMBER;
      hash = (53 * hash) + getCmd().hashCode();
      hash = (37 * hash) + WATER_FIELD_NUMBER;
      hash = (53 * hash) + getWater().hashCode();
      hash = (37 * hash) + PERSON_ID_FIELD_NUMBER;
      hash = (53 * hash) + getPersonId().hashCode();
      hash = (37 * hash) + GROUP_ID_FIELD_NUMBER;
      hash = (53 * hash) + getGroupId();
      if (getFeatureListCount() > 0) {
        hash = (37 * hash) + FEATURE_LIST_FIELD_NUMBER;
        hash = (53 * hash) + getFeatureListList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static TaskData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TaskData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TaskData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TaskData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TaskData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TaskData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TaskData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static TaskData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static TaskData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static TaskData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static TaskData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static TaskData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(TaskData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pro.add.TaskData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pro.add.TaskData)
        TaskDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return FeatureAdd.internal_static_pro_add_TaskData_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return FeatureAdd.internal_static_pro_add_TaskData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                TaskData.class, Builder.class);
      }

      // Construct using pro.add.FeatureAdd.TaskData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getFeatureListFieldBuilder();
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        cmd_ = "";

        water_ = "";

        personId_ = "";

        groupId_ = 0;

        if (featureListBuilder_ == null) {
          featureList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
        } else {
          featureListBuilder_.clear();
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return FeatureAdd.internal_static_pro_add_TaskData_descriptor;
      }

      @Override
      public TaskData getDefaultInstanceForType() {
        return TaskData.getDefaultInstance();
      }

      @Override
      public TaskData build() {
        TaskData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public TaskData buildPartial() {
        TaskData result = new TaskData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.cmd_ = cmd_;
        result.water_ = water_;
        result.personId_ = personId_;
        result.groupId_ = groupId_;
        if (featureListBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010)) {
            featureList_ = java.util.Collections.unmodifiableList(featureList_);
            bitField0_ = (bitField0_ & ~0x00000010);
          }
          result.featureList_ = featureList_;
        } else {
          result.featureList_ = featureListBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof TaskData) {
          return mergeFrom((TaskData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(TaskData other) {
        if (other == TaskData.getDefaultInstance()) return this;
        if (!other.getCmd().isEmpty()) {
          cmd_ = other.cmd_;
          onChanged();
        }
        if (!other.getWater().isEmpty()) {
          water_ = other.water_;
          onChanged();
        }
        if (!other.getPersonId().isEmpty()) {
          personId_ = other.personId_;
          onChanged();
        }
        if (other.getGroupId() != 0) {
          setGroupId(other.getGroupId());
        }
        if (featureListBuilder_ == null) {
          if (!other.featureList_.isEmpty()) {
            if (featureList_.isEmpty()) {
              featureList_ = other.featureList_;
              bitField0_ = (bitField0_ & ~0x00000010);
            } else {
              ensureFeatureListIsMutable();
              featureList_.addAll(other.featureList_);
            }
            onChanged();
          }
        } else {
          if (!other.featureList_.isEmpty()) {
            if (featureListBuilder_.isEmpty()) {
              featureListBuilder_.dispose();
              featureListBuilder_ = null;
              featureList_ = other.featureList_;
              bitField0_ = (bitField0_ & ~0x00000010);
              featureListBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getFeatureListFieldBuilder() : null;
            } else {
              featureListBuilder_.addAllMessages(other.featureList_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        TaskData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (TaskData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object cmd_ = "";
      /**
       * <code>string cmd = 1;</code>
       */
      public String getCmd() {
        Object ref = cmd_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          cmd_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string cmd = 1;</code>
       */
      public com.google.protobuf.ByteString
          getCmdBytes() {
        Object ref = cmd_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          cmd_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string cmd = 1;</code>
       */
      public Builder setCmd(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        cmd_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string cmd = 1;</code>
       */
      public Builder clearCmd() {
        
        cmd_ = getDefaultInstance().getCmd();
        onChanged();
        return this;
      }
      /**
       * <code>string cmd = 1;</code>
       */
      public Builder setCmdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        cmd_ = value;
        onChanged();
        return this;
      }

      private Object water_ = "";
      /**
       * <code>string water = 2;</code>
       */
      public String getWater() {
        Object ref = water_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          water_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string water = 2;</code>
       */
      public com.google.protobuf.ByteString
          getWaterBytes() {
        Object ref = water_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          water_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string water = 2;</code>
       */
      public Builder setWater(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        water_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string water = 2;</code>
       */
      public Builder clearWater() {
        
        water_ = getDefaultInstance().getWater();
        onChanged();
        return this;
      }
      /**
       * <code>string water = 2;</code>
       */
      public Builder setWaterBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        water_ = value;
        onChanged();
        return this;
      }

      private Object personId_ = "";
      /**
       * <code>string person_id = 3;</code>
       */
      public String getPersonId() {
        Object ref = personId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          personId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string person_id = 3;</code>
       */
      public com.google.protobuf.ByteString
          getPersonIdBytes() {
        Object ref = personId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          personId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string person_id = 3;</code>
       */
      public Builder setPersonId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        personId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string person_id = 3;</code>
       */
      public Builder clearPersonId() {
        
        personId_ = getDefaultInstance().getPersonId();
        onChanged();
        return this;
      }
      /**
       * <code>string person_id = 3;</code>
       */
      public Builder setPersonIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        personId_ = value;
        onChanged();
        return this;
      }

      private int groupId_ ;
      /**
       * <code>int32 group_id = 4;</code>
       */
      public int getGroupId() {
        return groupId_;
      }
      /**
       * <code>int32 group_id = 4;</code>
       */
      public Builder setGroupId(int value) {
        
        groupId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 group_id = 4;</code>
       */
      public Builder clearGroupId() {
        
        groupId_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<AddFeature> featureList_ =
        java.util.Collections.emptyList();
      private void ensureFeatureListIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          featureList_ = new java.util.ArrayList<AddFeature>(featureList_);
          bitField0_ |= 0x00000010;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          AddFeature, AddFeature.Builder, AddFeatureOrBuilder> featureListBuilder_;

      /**
       * <code>repeated .pro.add.AddFeature feature_list = 5;</code>
       */
      public java.util.List<AddFeature> getFeatureListList() {
        if (featureListBuilder_ == null) {
          return java.util.Collections.unmodifiableList(featureList_);
        } else {
          return featureListBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .pro.add.AddFeature feature_list = 5;</code>
       */
      public int getFeatureListCount() {
        if (featureListBuilder_ == null) {
          return featureList_.size();
        } else {
          return featureListBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .pro.add.AddFeature feature_list = 5;</code>
       */
      public AddFeature getFeatureList(int index) {
        if (featureListBuilder_ == null) {
          return featureList_.get(index);
        } else {
          return featureListBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .pro.add.AddFeature feature_list = 5;</code>
       */
      public Builder setFeatureList(
          int index, AddFeature value) {
        if (featureListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFeatureListIsMutable();
          featureList_.set(index, value);
          onChanged();
        } else {
          featureListBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .pro.add.AddFeature feature_list = 5;</code>
       */
      public Builder setFeatureList(
          int index, AddFeature.Builder builderForValue) {
        if (featureListBuilder_ == null) {
          ensureFeatureListIsMutable();
          featureList_.set(index, builderForValue.build());
          onChanged();
        } else {
          featureListBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .pro.add.AddFeature feature_list = 5;</code>
       */
      public Builder addFeatureList(AddFeature value) {
        if (featureListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFeatureListIsMutable();
          featureList_.add(value);
          onChanged();
        } else {
          featureListBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .pro.add.AddFeature feature_list = 5;</code>
       */
      public Builder addFeatureList(
          int index, AddFeature value) {
        if (featureListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFeatureListIsMutable();
          featureList_.add(index, value);
          onChanged();
        } else {
          featureListBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .pro.add.AddFeature feature_list = 5;</code>
       */
      public Builder addFeatureList(
          AddFeature.Builder builderForValue) {
        if (featureListBuilder_ == null) {
          ensureFeatureListIsMutable();
          featureList_.add(builderForValue.build());
          onChanged();
        } else {
          featureListBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .pro.add.AddFeature feature_list = 5;</code>
       */
      public Builder addFeatureList(
          int index, AddFeature.Builder builderForValue) {
        if (featureListBuilder_ == null) {
          ensureFeatureListIsMutable();
          featureList_.add(index, builderForValue.build());
          onChanged();
        } else {
          featureListBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .pro.add.AddFeature feature_list = 5;</code>
       */
      public Builder addAllFeatureList(
          Iterable<? extends AddFeature> values) {
        if (featureListBuilder_ == null) {
          ensureFeatureListIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, featureList_);
          onChanged();
        } else {
          featureListBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .pro.add.AddFeature feature_list = 5;</code>
       */
      public Builder clearFeatureList() {
        if (featureListBuilder_ == null) {
          featureList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
          onChanged();
        } else {
          featureListBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .pro.add.AddFeature feature_list = 5;</code>
       */
      public Builder removeFeatureList(int index) {
        if (featureListBuilder_ == null) {
          ensureFeatureListIsMutable();
          featureList_.remove(index);
          onChanged();
        } else {
          featureListBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .pro.add.AddFeature feature_list = 5;</code>
       */
      public AddFeature.Builder getFeatureListBuilder(
          int index) {
        return getFeatureListFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .pro.add.AddFeature feature_list = 5;</code>
       */
      public AddFeatureOrBuilder getFeatureListOrBuilder(
          int index) {
        if (featureListBuilder_ == null) {
          return featureList_.get(index);  } else {
          return featureListBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .pro.add.AddFeature feature_list = 5;</code>
       */
      public java.util.List<? extends AddFeatureOrBuilder>
           getFeatureListOrBuilderList() {
        if (featureListBuilder_ != null) {
          return featureListBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(featureList_);
        }
      }
      /**
       * <code>repeated .pro.add.AddFeature feature_list = 5;</code>
       */
      public AddFeature.Builder addFeatureListBuilder() {
        return getFeatureListFieldBuilder().addBuilder(
            AddFeature.getDefaultInstance());
      }
      /**
       * <code>repeated .pro.add.AddFeature feature_list = 5;</code>
       */
      public AddFeature.Builder addFeatureListBuilder(
          int index) {
        return getFeatureListFieldBuilder().addBuilder(
            index, AddFeature.getDefaultInstance());
      }
      /**
       * <code>repeated .pro.add.AddFeature feature_list = 5;</code>
       */
      public java.util.List<AddFeature.Builder>
           getFeatureListBuilderList() {
        return getFeatureListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          AddFeature, AddFeature.Builder, AddFeatureOrBuilder>
          getFeatureListFieldBuilder() {
        if (featureListBuilder_ == null) {
          featureListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              AddFeature, AddFeature.Builder, AddFeatureOrBuilder>(
                  featureList_,
                  ((bitField0_ & 0x00000010) == 0x00000010),
                  getParentForChildren(),
                  isClean());
          featureList_ = null;
        }
        return featureListBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:pro.add.TaskData)
    }

    // @@protoc_insertion_point(class_scope:pro.add.TaskData)
    private static final TaskData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new TaskData();
    }

    public static TaskData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TaskData>
        PARSER = new com.google.protobuf.AbstractParser<TaskData>() {
      @Override
      public TaskData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TaskData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TaskData> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<TaskData> getParserForType() {
      return PARSER;
    }

    @Override
    public TaskData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AddFeatureOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pro.add.AddFeature)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string feature_id = 1;</code>
     */
    String getFeatureId();
    /**
     * <code>string feature_id = 1;</code>
     */
    com.google.protobuf.ByteString
        getFeatureIdBytes();

    /**
     * <code>int32 eye_flag = 2;</code>
     */
    int getEyeFlag();

    /**
     * <code>int32 iris_enrLength = 3;</code>
     */
    int getIrisEnrLength();

    /**
     * <code>bytes iris_enrTemplate = 4;</code>
     */
    com.google.protobuf.ByteString getIrisEnrTemplate();

    /**
     * <code>int32 iris_recLength = 5;</code>
     */
    int getIrisRecLength();

    /**
     * <code>bytes iris_recTemplate = 6;</code>
     */
    com.google.protobuf.ByteString getIrisRecTemplate();
  }
  /**
   * Protobuf type {@code pro.add.AddFeature}
   */
  public  static final class AddFeature extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:pro.add.AddFeature)
      AddFeatureOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AddFeature.newBuilder() to construct.
    private AddFeature(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AddFeature() {
      featureId_ = "";
      eyeFlag_ = 0;
      irisEnrLength_ = 0;
      irisEnrTemplate_ = com.google.protobuf.ByteString.EMPTY;
      irisRecLength_ = 0;
      irisRecTemplate_ = com.google.protobuf.ByteString.EMPTY;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AddFeature(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();

              featureId_ = s;
              break;
            }
            case 16: {

              eyeFlag_ = input.readInt32();
              break;
            }
            case 24: {

              irisEnrLength_ = input.readInt32();
              break;
            }
            case 34: {

              irisEnrTemplate_ = input.readBytes();
              break;
            }
            case 40: {

              irisRecLength_ = input.readInt32();
              break;
            }
            case 50: {

              irisRecTemplate_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return FeatureAdd.internal_static_pro_add_AddFeature_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return FeatureAdd.internal_static_pro_add_AddFeature_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              AddFeature.class, Builder.class);
    }

    public static final int FEATURE_ID_FIELD_NUMBER = 1;
    private volatile Object featureId_;
    /**
     * <code>string feature_id = 1;</code>
     */
    public String getFeatureId() {
      Object ref = featureId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        featureId_ = s;
        return s;
      }
    }
    /**
     * <code>string feature_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFeatureIdBytes() {
      Object ref = featureId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        featureId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EYE_FLAG_FIELD_NUMBER = 2;
    private int eyeFlag_;
    /**
     * <code>int32 eye_flag = 2;</code>
     */
    public int getEyeFlag() {
      return eyeFlag_;
    }

    public static final int IRIS_ENRLENGTH_FIELD_NUMBER = 3;
    private int irisEnrLength_;
    /**
     * <code>int32 iris_enrLength = 3;</code>
     */
    public int getIrisEnrLength() {
      return irisEnrLength_;
    }

    public static final int IRIS_ENRTEMPLATE_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString irisEnrTemplate_;
    /**
     * <code>bytes iris_enrTemplate = 4;</code>
     */
    public com.google.protobuf.ByteString getIrisEnrTemplate() {
      return irisEnrTemplate_;
    }

    public static final int IRIS_RECLENGTH_FIELD_NUMBER = 5;
    private int irisRecLength_;
    /**
     * <code>int32 iris_recLength = 5;</code>
     */
    public int getIrisRecLength() {
      return irisRecLength_;
    }

    public static final int IRIS_RECTEMPLATE_FIELD_NUMBER = 6;
    private com.google.protobuf.ByteString irisRecTemplate_;
    /**
     * <code>bytes iris_recTemplate = 6;</code>
     */
    public com.google.protobuf.ByteString getIrisRecTemplate() {
      return irisRecTemplate_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getFeatureIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, featureId_);
      }
      if (eyeFlag_ != 0) {
        output.writeInt32(2, eyeFlag_);
      }
      if (irisEnrLength_ != 0) {
        output.writeInt32(3, irisEnrLength_);
      }
      if (!irisEnrTemplate_.isEmpty()) {
        output.writeBytes(4, irisEnrTemplate_);
      }
      if (irisRecLength_ != 0) {
        output.writeInt32(5, irisRecLength_);
      }
      if (!irisRecTemplate_.isEmpty()) {
        output.writeBytes(6, irisRecTemplate_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getFeatureIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, featureId_);
      }
      if (eyeFlag_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, eyeFlag_);
      }
      if (irisEnrLength_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, irisEnrLength_);
      }
      if (!irisEnrTemplate_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, irisEnrTemplate_);
      }
      if (irisRecLength_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, irisRecLength_);
      }
      if (!irisRecTemplate_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, irisRecTemplate_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof AddFeature)) {
        return super.equals(obj);
      }
      AddFeature other = (AddFeature) obj;

      boolean result = true;
      result = result && getFeatureId()
          .equals(other.getFeatureId());
      result = result && (getEyeFlag()
          == other.getEyeFlag());
      result = result && (getIrisEnrLength()
          == other.getIrisEnrLength());
      result = result && getIrisEnrTemplate()
          .equals(other.getIrisEnrTemplate());
      result = result && (getIrisRecLength()
          == other.getIrisRecLength());
      result = result && getIrisRecTemplate()
          .equals(other.getIrisRecTemplate());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FEATURE_ID_FIELD_NUMBER;
      hash = (53 * hash) + getFeatureId().hashCode();
      hash = (37 * hash) + EYE_FLAG_FIELD_NUMBER;
      hash = (53 * hash) + getEyeFlag();
      hash = (37 * hash) + IRIS_ENRLENGTH_FIELD_NUMBER;
      hash = (53 * hash) + getIrisEnrLength();
      hash = (37 * hash) + IRIS_ENRTEMPLATE_FIELD_NUMBER;
      hash = (53 * hash) + getIrisEnrTemplate().hashCode();
      hash = (37 * hash) + IRIS_RECLENGTH_FIELD_NUMBER;
      hash = (53 * hash) + getIrisRecLength();
      hash = (37 * hash) + IRIS_RECTEMPLATE_FIELD_NUMBER;
      hash = (53 * hash) + getIrisRecTemplate().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static AddFeature parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AddFeature parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AddFeature parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AddFeature parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AddFeature parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AddFeature parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AddFeature parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static AddFeature parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static AddFeature parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static AddFeature parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static AddFeature parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static AddFeature parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(AddFeature prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pro.add.AddFeature}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pro.add.AddFeature)
        AddFeatureOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return FeatureAdd.internal_static_pro_add_AddFeature_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return FeatureAdd.internal_static_pro_add_AddFeature_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                AddFeature.class, Builder.class);
      }

      // Construct using pro.add.FeatureAdd.AddFeature.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        featureId_ = "";

        eyeFlag_ = 0;

        irisEnrLength_ = 0;

        irisEnrTemplate_ = com.google.protobuf.ByteString.EMPTY;

        irisRecLength_ = 0;

        irisRecTemplate_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return FeatureAdd.internal_static_pro_add_AddFeature_descriptor;
      }

      @Override
      public AddFeature getDefaultInstanceForType() {
        return AddFeature.getDefaultInstance();
      }

      @Override
      public AddFeature build() {
        AddFeature result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public AddFeature buildPartial() {
        AddFeature result = new AddFeature(this);
        result.featureId_ = featureId_;
        result.eyeFlag_ = eyeFlag_;
        result.irisEnrLength_ = irisEnrLength_;
        result.irisEnrTemplate_ = irisEnrTemplate_;
        result.irisRecLength_ = irisRecLength_;
        result.irisRecTemplate_ = irisRecTemplate_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof AddFeature) {
          return mergeFrom((AddFeature)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(AddFeature other) {
        if (other == AddFeature.getDefaultInstance()) return this;
        if (!other.getFeatureId().isEmpty()) {
          featureId_ = other.featureId_;
          onChanged();
        }
        if (other.getEyeFlag() != 0) {
          setEyeFlag(other.getEyeFlag());
        }
        if (other.getIrisEnrLength() != 0) {
          setIrisEnrLength(other.getIrisEnrLength());
        }
        if (other.getIrisEnrTemplate() != com.google.protobuf.ByteString.EMPTY) {
          setIrisEnrTemplate(other.getIrisEnrTemplate());
        }
        if (other.getIrisRecLength() != 0) {
          setIrisRecLength(other.getIrisRecLength());
        }
        if (other.getIrisRecTemplate() != com.google.protobuf.ByteString.EMPTY) {
          setIrisRecTemplate(other.getIrisRecTemplate());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        AddFeature parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (AddFeature) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object featureId_ = "";
      /**
       * <code>string feature_id = 1;</code>
       */
      public String getFeatureId() {
        Object ref = featureId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          featureId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string feature_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getFeatureIdBytes() {
        Object ref = featureId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          featureId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string feature_id = 1;</code>
       */
      public Builder setFeatureId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        featureId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string feature_id = 1;</code>
       */
      public Builder clearFeatureId() {
        
        featureId_ = getDefaultInstance().getFeatureId();
        onChanged();
        return this;
      }
      /**
       * <code>string feature_id = 1;</code>
       */
      public Builder setFeatureIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        featureId_ = value;
        onChanged();
        return this;
      }

      private int eyeFlag_ ;
      /**
       * <code>int32 eye_flag = 2;</code>
       */
      public int getEyeFlag() {
        return eyeFlag_;
      }
      /**
       * <code>int32 eye_flag = 2;</code>
       */
      public Builder setEyeFlag(int value) {
        
        eyeFlag_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 eye_flag = 2;</code>
       */
      public Builder clearEyeFlag() {
        
        eyeFlag_ = 0;
        onChanged();
        return this;
      }

      private int irisEnrLength_ ;
      /**
       * <code>int32 iris_enrLength = 3;</code>
       */
      public int getIrisEnrLength() {
        return irisEnrLength_;
      }
      /**
       * <code>int32 iris_enrLength = 3;</code>
       */
      public Builder setIrisEnrLength(int value) {
        
        irisEnrLength_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 iris_enrLength = 3;</code>
       */
      public Builder clearIrisEnrLength() {
        
        irisEnrLength_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString irisEnrTemplate_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes iris_enrTemplate = 4;</code>
       */
      public com.google.protobuf.ByteString getIrisEnrTemplate() {
        return irisEnrTemplate_;
      }
      /**
       * <code>bytes iris_enrTemplate = 4;</code>
       */
      public Builder setIrisEnrTemplate(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        irisEnrTemplate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes iris_enrTemplate = 4;</code>
       */
      public Builder clearIrisEnrTemplate() {
        
        irisEnrTemplate_ = getDefaultInstance().getIrisEnrTemplate();
        onChanged();
        return this;
      }

      private int irisRecLength_ ;
      /**
       * <code>int32 iris_recLength = 5;</code>
       */
      public int getIrisRecLength() {
        return irisRecLength_;
      }
      /**
       * <code>int32 iris_recLength = 5;</code>
       */
      public Builder setIrisRecLength(int value) {
        
        irisRecLength_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 iris_recLength = 5;</code>
       */
      public Builder clearIrisRecLength() {
        
        irisRecLength_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString irisRecTemplate_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes iris_recTemplate = 6;</code>
       */
      public com.google.protobuf.ByteString getIrisRecTemplate() {
        return irisRecTemplate_;
      }
      /**
       * <code>bytes iris_recTemplate = 6;</code>
       */
      public Builder setIrisRecTemplate(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        irisRecTemplate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes iris_recTemplate = 6;</code>
       */
      public Builder clearIrisRecTemplate() {
        
        irisRecTemplate_ = getDefaultInstance().getIrisRecTemplate();
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:pro.add.AddFeature)
    }

    // @@protoc_insertion_point(class_scope:pro.add.AddFeature)
    private static final AddFeature DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new AddFeature();
    }

    public static AddFeature getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AddFeature>
        PARSER = new com.google.protobuf.AbstractParser<AddFeature>() {
      @Override
      public AddFeature parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AddFeature(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AddFeature> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<AddFeature> getParserForType() {
      return PARSER;
    }

    @Override
    public AddFeature getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pro_add_TaskData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pro_add_TaskData_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pro_add_AddFeature_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pro_add_AddFeature_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\020FeatureAdd.proto\022\007pro.add\"v\n\010TaskData\022" +
      "\013\n\003cmd\030\001 \001(\t\022\r\n\005water\030\002 \001(\t\022\021\n\tperson_id" +
      "\030\003 \001(\t\022\020\n\010group_id\030\004 \001(\005\022)\n\014feature_list" +
      "\030\005 \003(\0132\023.pro.add.AddFeature\"\226\001\n\nAddFeatu" +
      "re\022\022\n\nfeature_id\030\001 \001(\t\022\020\n\010eye_flag\030\002 \001(\005" +
      "\022\026\n\016iris_enrLength\030\003 \001(\005\022\030\n\020iris_enrTemp" +
      "late\030\004 \001(\014\022\026\n\016iris_recLength\030\005 \001(\005\022\030\n\020ir" +
      "is_recTemplate\030\006 \001(\014b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_pro_add_TaskData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_pro_add_TaskData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pro_add_TaskData_descriptor,
        new String[] { "Cmd", "Water", "PersonId", "GroupId", "FeatureList", });
    internal_static_pro_add_AddFeature_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_pro_add_AddFeature_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pro_add_AddFeature_descriptor,
        new String[] { "FeatureId", "EyeFlag", "IrisEnrLength", "IrisEnrTemplate", "IrisRecLength", "IrisRecTemplate", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
